version: '3'

services:
  web:
    build: .
    container_name: smilabustime_bot
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    env_file:
      - .env
    
