version: '3'

services:
  bot:
    build: .
    container_name: smilabustime_bot
    depends_on:
      - mysql
    restart: always
    ports:
      - "36000:36000"
    env_file: .env

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
      
  
    
